PREFIX = \/usr\/local\/lib\/mafft
#CC = gcc  -O3 
CC = gcc  -O3  -march=i686 -ffast-math -fno-math-errno -fomit-frame-pointer -malign-double -malign-loops=3 -malign-functions=3
PROGS = dvtditr dndfast4 sextet5 tbfast galn score getlag dndpre
SCRIPTS = fftns fftnsi nwns nwnsi mafft
OBJTBFAST = mtxutl.o io.o mltaln9.o tddis.o constants.o A+++alignmm.o \
		    Falign.o SAalignmm.o Calignm1.o iteration.o \
			tbfast.o dp.o fft.o fftFunctions.o
OBJTDITR = mtxutl.o io.o mltaln9.o tddis.o constants.o nj.o  A+++alignmm.o \
		   Calignm1.o Falign.o fftFunctions.o fft.o iteration.o \
		   tditeration.o tditr.o dp.o SAalignmm.o treeOperation.o
OBJDVTDITR = mtxutl.o io.o mltaln9.o tddis.o constants.o nj.o  A+++alignmm.o \
			Calignm1.o Falign.o fftFunctions.o fft.o iteration.o \
			tditeration.o dvtditr.o dp.o SAalignmm.o treeOperation.o
OBJGETLAG = mtxutl.o io.o mltaln9.o tddis.o constants.o A+++alignmm.o \
		    Falign.o SAalignmm.o Calignm1.o iteration.o \
			getlag.o dp.o fft.o fftFunctions.o
OBJGAPFILL = mtxutl.o io.o constants.o gapfill.o
OBJDNDFAST4 = dndfast4.o io.o constants.o mtxutl.o mltaln9.o tddis.o
OBJDNDFAST6 = dndfast6.o io.o constants.o mtxutl.o mltaln9.o tddis.o
OBJSEXTET5 = io.o constants.o mtxutl.o mltaln9.o tddis.o sextet5.o
OBJSEXTET6 = io.o constants.o mtxutl.o mltaln9.o tddis.o sextet6.o
OBJTRIPLET6 = io.o constants.o mtxutl.o mltaln9.o tddis.o triplet6.o
OBJTRIPLET5 = io.o constants.o mtxutl.o mltaln9.o tddis.o triplet5.o
OBJOCTET4 = io.o constants.o mtxutl.o mltaln9.o tddis.o octet4.o
OBJDNDPRE = dndpre.o io.o constants.o mtxutl.o mltaln9.o
OBJGALN = io.o mtxutl.o mltaln9.o tddis.o constants.o A+++alignmm.o \
          Calignm1.o SAalignmm.o Falign.o fftFunctions.o fft.o galn.o dp.o
OBJSCORE = io.o mtxutl.o mltaln9.o score.o constants.o

HEADER = mltaln.h mtxutl.h
DPHEADER = dp.h
FFTHEADER = fft.h


#CFLAG =  -Wunused -Wreturn-type -Wshadow -pg
#CFLAG =   -ansi -pedantic
LIBS = -lm

all : $(PROGS) $(SCRIPTS)
	cp $(PROGS) ../binaries
	cp $(SCRIPTS) ../scripts
	chmod 755 ../binaries/*
	chmod 755 ../scripts/*
	@echo done.

fftns: fftns.tmpl
	sed "s/_PREFIX/$(PREFIX)/" fftns.tmpl  > fftns
fftnsi: fftnsi.tmpl
	sed "s/_PREFIX/$(PREFIX)/" fftnsi.tmpl > fftnsi
nwns: nwns.tmpl
	sed "s/_PREFIX/$(PREFIX)/" nwns.tmpl   > nwns
nwnsi: nwnsi.tmpl
	sed "s/_PREFIX/$(PREFIX)/" nwnsi.tmpl  > nwnsi
mafft: mafft.tmpl
	sed "s/_PREFIX/$(PREFIX)/" mafft.tmpl  > mafft

ord : $(OBJORD)
	$(CC) -o $@ $(OBJORD) $(CFLAG) $(LIBS)

tbfast : $(OBJTBFAST)
	$(CC) -o $@ $(OBJTBFAST) $(CFLAG) $(LIBS)

getlag : $(OBJGETLAG)
	$(CC) -o $@ $(OBJGETLAG) $(CFLAG) $(LIBS)

tditr : $(OBJTDITR)
	$(CC) -o $@ $(OBJTDITR) $(CFLAG) $(LIBS)

dvtditr : $(OBJDVTDITR)
	$(CC) -o $@ $(OBJDVTDITR) $(CFLAG) $(LIBS)

galn : $(OBJGALN)
	$(CC) -o $@ $(OBJGALN) $(CFLAG) $(LIBS)

gapfill : $(OBJGAPFILL)
	$(CC) -o $@ $(OBJGAPFILL) $(CFLAG) $(LIBS)

dndfast4 : $(OBJDNDFAST4)
	$(CC) -o $@ $(OBJDNDFAST4) $(CFLAG) $(LIBS)

dndfast6 : $(OBJDNDFAST6)
	$(CC) -o $@ $(OBJDNDFAST6) $(CFLAG) $(LIBS)

dndfast3 : $(OBJDNDFAST3)
	$(CC) -o $@ $(OBJDNDFAST3) $(CFLAG) $(LIBS)

triplet : $(OBJTRIPLET)
	$(CC) -o $@ $(OBJTRIPLET) $(CFLAG) $(LIBS)

triplet3 : $(OBJTRIPLET3)
	$(CC) -o $@ $(OBJTRIPLET3) $(CFLAG) $(LIBS)

sextet3 : $(OBJSEXTET3)
	$(CC) -o $@ $(OBJSEXTET3) $(CFLAG) $(LIBS)

sextet4 : $(OBJSEXTET4)
	$(CC) -o $@ $(OBJSEXTET4) $(CFLAG) $(LIBS)

sextet5 : $(OBJSEXTET5)
	$(CC) -o $@ $(OBJSEXTET5) $(CFLAG) $(LIBS)

sextet6 : $(OBJSEXTET6)
	$(CC) -o $@ $(OBJSEXTET6) $(CFLAG) $(LIBS)

triplet5 : $(OBJTRIPLET5)
	$(CC) -o $@ $(OBJTRIPLET5) $(CFLAG) $(LIBS)

triplet6 : $(OBJTRIPLET6)
	$(CC) -o $@ $(OBJTRIPLET6) $(CFLAG) $(LIBS)

octet4 : $(OBJOCTET4)
	$(CC) -o $@ $(OBJOCTET4) $(CFLAG) $(LIBS)

dndpre : $(OBJDNDPRE)
	$(CC) -o $@ $(OBJDNDPRE) $(CFLAG) $(LIBS)

score : $(OBJSCORE)
	$(CC) -o $@ $(OBJSCORE) $(CFLAG) $(LIBS)

genMtx : $(OBJGENMTX)
	$(CC) -o $@ $(OBJGENMTX) $(CFLAG) $(LIBS)

gapfill.o : gapfill.c $(HEADER)
	$(CC) $(CFLAG) -c gapfill.c

mltaln9.o : mltaln9.c $(HEADER)
	$(CC) $(CFLAG) -c mltaln9.c

tddis.o : tddis.c $(HEADER)
	$(CC) $(CFLAG) -c tddis.c

constants.o : constants.c miyata.h miyata5.h gonnet.h DNA.h JTT.c $(HEADER)
	$(CC) $(CFLAG) -c constants.c

dp.o : dp.c 
	$(CC) $(CFLAG) -c dp.c

Calignm1.o : Calignm1.c $(HEADER) $(DPHEADER)
	$(CC) $(CFLAG) -c Calignm1.c

#A+++alignmm.o : SA+++alignmm.c $(HEADER) $(DPHEADER)
#	$(CC) $(CFLAG) -c SA+++alignmm.c -o A+++alignmm.o

A+++alignmm.o : Salignmm.c $(HEADER) $(DPHEADER)
	$(CC) $(CFLAG) -c Salignmm.c -o A+++alignmm.o

SAalignmm.o : SAalignmm.c $(HEADER) $(DPHEADER)
	$(CC) $(CFLAG) -c SAalignmm.c -o SAalignmm.o

ord.o : ord.c $(HEADER)
	$(CC) $(CFLAG) -c ord.c

1itr.o : 1itr.c $(HEADER)
	$(CC) $(CFLAG) -c 1itr.c

iteration.o : iteration.c $(HEADER)
	$(CC) $(CFLAG) -c iteration.c

tb.o : tb.c $(HEADER)
	$(CC) $(CFLAG) -c tb.c

tbfast.o : tbfast.c $(HEADER) $(FFTHEADER)
	$(CC) $(CFLAG) -c tbfast.c

getlag.o : getlag.c $(HEADER) $(FFTHEADER)
	$(CC) $(CFLAG) -c getlag.c

tditr.o : tditr.c $(HEADER)
	 $(CC) $(CFLAG) -c tditr.c

dvtditr.o : dvtditr.c $(HEADER)
	 $(CC) $(CFLAG) -c dvtditr.c

tditeration.o : tditeration.c $(HEADER)
	 $(CC) $(CFLAG) -c tditeration.c

galn.o : galn.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c galn.c

dndfast4.o : dndfast4.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c dndfast4.c

dndfast6.o : dndfast6.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c dndfast6.c

dndfast3.o : dndfast3.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c dndfast3.c

dndpre.o : dndpre.c $(HEADER)
	$(CC) $(CFLAG) -c dndpre.c

io.o : io.c $(HEADER) $(FFTHEADER)
	$(CC) $(CFLAG) -c io.c

nj.o : nj.c $(HEADER)
	$(CC) $(CFLAG) -c nj.c

treeOperation.o : treeOperation.c $(HEADER)
	$(CC) $(CFLAG) -c treeOperation.c

sextet5.o : sextet5.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c sextet5.c

sextet6.o : sextet6.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c sextet6.c

triplet5.o : triplet5.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c triplet5.c

triplet6.o : triplet6.c $(HEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c triplet6.c

fft.o : fft.c $(HEADER) $(FFTHEADER)
	$(CC) $(CFLAG) -c fft.c -O0

fftFunctions.o : fftFunctions.c $(HEADER) $(FFTHEADER)
	$(CC) $(CFLAG) -c fftFunctions.c

Falign.o : Falign.c $(HEADER) $(FFTHEADER) $(MTXHEADER)
	$(CC) $(CFLAG) -c Falign.c

mtxutl.o : mtxutl.c 
	$(CC) $(CFLAG) -c mtxutl.c

score.o : score.c $(HEADER)
	$(CC) $(CFLAG) -c score.c

clean :
	rm -f *.o *.a *.exe *~ $(PROGS)  $(SCRIPTS)
	rm -f ../binaries/* ../scripts/*
