#! /bin/sh 
if [ $MAFFT_BINARIES ]; then 
	prefix=$MAFFT_BINARIES
else
	prefix=/usr/local/lib/mafft
fi

param=""
param_it=" -x "
while [ $# -gt 1 ];
do
	if [ $1 = "--all-positive" ]; then 
		param=" -h -0.82 "
	elif [ $1 = "--nj" ]; then 
		param_it=" -n "
	fi
	shift
done;

#TMPFILE=`mktemp  -d ${tempfoo}.XXXXXXX` || exit 1
TMPFILE=/tmp/`basename $0`.`whoami`.$$.`date +%y%m%d%H%M%S`
umask 077
mkdir  $TMPFILE  || exit 1
trap "rm -r $TMPFILE; exit 1" 2
if [ $# -eq 1 ]; then
	tr "\r" "\n" < $1 > $TMPFILE/infile                || exit 1
#elif [ $# -eq 0 ]; then
#	cat > $TMPFILE/infile;
else
	rm -r $TMPFILE
	echo "Usage: `basename $0` [--all-positive] [--nj] inputfile (fasta format)" > /dev/tty; 
	exit 1;
fi

(
cd $TMPFILE;
if [ -s infile ]; then
	$prefix/sextet5             < infile  > /dev/null || exit 1
	$prefix/tbfast -Ax  $param  < infile  > /dev/null || exit 1
	$prefix/tbfast -JAx $param  < pre     > /dev/null || exit 1
	$prefix/dndpre              < pre     > /dev/null || exit 1
	$prefix/dvtditr -At $param $param_it < pre     > /dev/null || exit 1
	cat pre
	exit 0;
else
	echo "Cannot open $TMPFILE/infile." > /dev/tty; exit 1;
fi
)

rm -r $TMPFILE
exit 0;
